# Generated by Django 2.1.5 on 2019-02-18 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Types', models.CharField(choices=[('LM', 'Lawn Mowing'), ('SS', 'Snow Shoveling'), ('DW', 'Dog Walking'), ('PS', 'Pet Sitting'), ('BS', 'Baby Sitting'), ('C', 'Cleaning'), ('M', 'Moving'), ('O', 'Other')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay', models.FloatField()),
                ('Location', models.TextField()),
                ('DateTime', models.DateTimeField()),
                ('Description', models.TextField()),
                ('JobType', models.CharField(choices=[('LM', 'Lawn Mowing'), ('SS', 'Snow Shoveling'), ('DW', 'Dog Walking'), ('PS', 'Pet Sitting'), ('BS', 'Baby Sitting'), ('C', 'Cleaning'), ('M', 'Moving'), ('O', 'Other')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classification', models.CharField(choices=[('PI', 'Payment Issue'), ('V', 'Violence'), ('NS', 'No show'), ('S', 'Scam'), ('O', 'Other')], max_length=100)),
                ('Details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.TextField()),
                ('Password', models.TextField()),
                ('FirstName', models.TextField()),
                ('Description', models.TextField()),
                ('Age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.User')),
                ('Posts', models.ManyToManyField(to='Main.Post')),
                ('Reviews', models.ManyToManyField(to='Main.Review')),
            ],
            bases=('Main.user',),
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.User')),
                ('Location', models.TextField()),
                ('IntJob', models.ManyToManyField(to='Main.Post')),
                ('PrefType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.JobChoices')),
                ('Reviews', models.ManyToManyField(to='Main.Review')),
            ],
            bases=('Main.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='Contacts',
            field=models.ManyToManyField(related_name='_user_Contacts_+', to='Main.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='Reports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Report'),
        ),
    ]
