# Generated by Django 2.1.5 on 2019-03-19 22:38

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Types', models.CharField(choices=[('LM', 'Lawn Mowing'), ('SS', 'Snow Shoveling'), ('DW', 'Dog Walking'), ('PS', 'Pet Sitting'), ('BS', 'Baby Sitting'), ('C', 'Cleaning'), ('M', 'Moving'), ('O', 'Other')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay', models.FloatField()),
                ('Location', models.TextField()),
                ('DateTime', models.DateTimeField()),
                ('Description', models.TextField()),
                ('JobType', models.CharField(choices=[('LM', 'Lawn Mowing'), ('SS', 'Snow Shoveling'), ('DW', 'Dog Walking'), ('PS', 'Pet Sitting'), ('BS', 'Baby Sitting'), ('C', 'Cleaning'), ('M', 'Moving'), ('O', 'Other')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=60)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Age', models.SmallIntegerField()),
                ('Portrait', models.ImageField(blank=True, null=True, upload_to=Main.models.get_image_path)),
                ('Contacts', models.ManyToManyField(blank=True, related_name='_profile_Contacts_+', to='Main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classification', models.CharField(choices=[('PI', 'Payment Issue'), ('V', 'Violence'), ('NS', 'No show'), ('S', 'Scam'), ('O', 'Other')], max_length=100)),
                ('Details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.TextField(blank=True, null=True)),
                ('IntJob', models.ManyToManyField(blank=True, to='Main.Post')),
                ('PrefType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.JobChoices')),
                ('Reviews', models.ManyToManyField(blank=True, to='Main.Review')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Report'),
        ),
        migrations.AddField(
            model_name='profile',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creator',
            name='Posts',
            field=models.ManyToManyField(blank=True, to='Main.Post'),
        ),
        migrations.AddField(
            model_name='creator',
            name='Reviews',
            field=models.ManyToManyField(blank=True, to='Main.Review'),
        ),
        migrations.AddField(
            model_name='creator',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
