# Generated by Django 2.1.5 on 2019-03-17 08:07

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=60)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Age', models.SmallIntegerField()),
                ('Portrait', models.ImageField(blank=True, null=True, upload_to=Main.models.get_image_path)),
                ('Contacts', models.ManyToManyField(blank=True, related_name='_profile_Contacts_+', to='Main.Profile')),
                ('Reports', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Report')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Contacts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Reports',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User',
        ),
        migrations.AlterField(
            model_name='creator',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='Location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='PrefType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.JobChoices'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
