# Generated by Django 2.1.5 on 2019-02-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20190221_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='Posts',
            field=models.ManyToManyField(blank=True, to='Main.Post'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='Reviews',
            field=models.ManyToManyField(blank=True, to='Main.Review'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='IntJob',
            field=models.ManyToManyField(blank=True, to='Main.Post'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='Reviews',
            field=models.ManyToManyField(blank=True, to='Main.Review'),
        ),
    ]
