# Generated by Django 2.1.5 on 2019-02-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20190221_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='Location',
            field=models.TextField(blank=True),
        ),
    ]
